#!/bin/sh
# (C) Copyleft by Hrtk

_dmenu(){
	cat - | dmenu -b -l 10 -fn "$FONT" -i
}

FONT="Source\ Code\ Pro-20"
CONFIG=~/.clipbox
if [[ ! -f $CONFIG ]]; then
	>&2 echo "No $CONFIG file found"
	echo "No $CONFIG file found" | _dmenu 
	exit 10
fi

sed '/^[[:space:]]*$/d' $CONFIG | _dmenu | xargs -d "\n" xdotool type
