#!/bin/sh
# (C) Copyleft by Hrtk

_dmenu(){
	dmenu -b -l 10 -fn "$FONT" -i
}

#TODO: mulitine entry support
process(){
	if [[ "$1" == 'add' ]]; then
		echo 
		#TODO: add 
	else
		echo $1 | xargs -d "\n" xdotool type
	fi
}

FONT="Source\ Code\ Pro-20"
CONFIG=~/.clipbox
if [[ ! -f $CONFIG ]]; then
	>&2 echo "No $CONFIG file found"
	echo "No $CONFIG file found" | _dmenu 
	exit 10
fi

process "$(sed '/^[[:space:]]*$/d' $CONFIG | _dmenu)"
