#!/bin/sh
# (C) Copyleft by Hrtk

_dmenu(){
	cat - | dmenu -l 10 -fn "$FONT" -i
}

FONT="Source\ Code\ Pro-20"
if [[ ! -f ~/.i3clipbox ]]; then
	>&2 echo "No ~/.i3clipbox file found"
	echo "No ~/.i3clipbox file found" | _dmenu 
	exit 10
fi

 _dmenu < ~/.i3clipbox | xargs -d "\n" xdotool type
