#!/bin/bash
# urlencode <string>
old_lc_collate=$LC_COLLATE
LC_COLLATE=C


param=$(get_arg_or_stdin "$*")
length="${#param}"
for (( i = 0; i < length; i++ )); do
c="${param:i:1}"
case $c in
[a-zA-Z0-9.~_-]) printf "%s" "$c" ;;
*) printf '%%%02X' "'$c" ;;
esac
done

LC_COLLATE=$old_lc_collate

# via: https://gist.github.com/cdown/1163649
